check50:
  checks:
    hello:
      - run: python3 hello.py
        stdout: Hello, World!
        exit: 0
submit50:
  checks:
    hello:
      - run: python3 hello.py
        stdout: Hello, World!
        exit: 0
