check50:
  checks:
    monkey:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
submit50:
  checks:
    monkey:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
