check50:
  checks:
    brr:
      - run: python3 c_to_f.py
        stdin:  32
        stdout: That's 89.6 degrees in Fahrenheit.
        exit: 0
    ahh:
      - run: python3 c_to_f.py
        stdin:  20
        stdout: That's 68.0 degrees in Fahrenheit.
        exit: 0
submit50:
  checks:
    brr:
      - run: python3 c_to_f.py
        stdin:  32
        stdout: That's 89.6 degrees in Fahrenheit.
        exit: 0
    ahh:
      - run: python3 c_to_f.py
        stdin:  20
        stdout: That's 68.0 degrees in Fahrenheit.
        exit: 0
